dataVIZ/urls.py
from django.conf.urls import *
from dataVIZ import views
from django.contrib.staticfiles.urls import static
from django.conf import settings
from django.conf.urls.static import static

app_name = "dataVIZ"

urlpatterns = [
    url(r'^$',views.index,name='index'),
    #url(r'insert/',views.insert,name='insert'),
    url(r'records/$',views.records,name='records'),
    #url(r'^listview/',views.records,name='listview'),
    #url(r'records/',views.IndexView.as_view(),name='records'),
    
    # /records/id/
    #url(r'^(?P<student_id>[0-9]+)/$',views.details,name='studentDetails'),
    
    #studentDetails/student_id
    url(r'^studentDetails/([0-9]+)/$',views.student_details_page,name='studentDetails'),
    
    #VIEWS (ListView, DetailView,CreateView etc.)
    url(r'^listview/',views.IndexView.as_view(),name='listview'),
    #url(r'^detailview/(?P<pk>[0-9]+)/$',views.DetailView.as_view(),name='detailview'),
    url(r'^add/',views.StudentInformationCreate.as_view(),name='addstudent'),
    url(r'^update/(?P<pk>[0-9]+)/$',views.StudentUdpate.as_view(),name='update-student'),
    url(r'^delete/(?P<pk>[0-9]+)/$',views.DeleteStudent.as_view(),name='delete-student'),
    url(r'^predict/([0-9]+)/$',views.predict,name='predict')
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/urls.py
from django.conf.urls import *
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #url(r'^$',include('dataVIZ.urls')),
    url(r'^',include('dataVIZ.urls')),
    #url(r'^',include('personal.urls')),
    #url(r'^contact/',include('personal.urls')),
    #url(r'^blog/',include('blog.urls')),
    #url(r'^insert/',include('dataVIZ.urls')),
    url(r'records/',include('dataVIZ.urls')),
    url(r'^detailview/',include('dataVIZ.urls')),
    url(r'^listview/',include('dataVIZ.urls'))
]

dataVIZ/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.core.validators import MinValueValidator, MaxValueValidator    

class studentInformation(models.Model):
    firstname = models.CharField(max_length=20)
    lastname = models.CharField(max_length=20)
    exam1_marks = models.IntegerField(validators=[MinValueValidator(0),
                                       MaxValueValidator(100)])
    exam2_marks = models.IntegerField(validators=[MinValueValidator(0),
                                       MaxValueValidator(100)])
    
    def get_absolute_url(self):
        return reverse('dataVIZ:detailview',kwargs={'pk':self.pk})
    
    def __unicode__(self):
        return self.firstname
    

    

dataVIZ/forms.py
from django import forms
from dataVIZ.models import studentInformation

class studentInformationForm(forms.ModelForm):
    firstname = forms.CharField(max_length=20)
    lastname = forms.CharField(max_length=20)
    exam1_marks = forms.IntegerField(max_value=100,min_value=0)
    exam2_marks = forms.IntegerField(max_value=100,min_value=0)

dataVIZ/views.py
from django.http import Http404
from django.http import HttpResponse
from django.shortcuts import render
from django.template import loader
from dataVIZ.forms import studentInformationForm
from dataVIZ.models import studentInformation
from django.views import generic
from django.core.paginator import Paginator
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
import os
#in order to get static files
from django.contrib.staticfiles.templatetags.staticfiles import static
from django.contrib.staticfiles import storage

from django.views.decorators import csrf

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
from scipy.special import expit
from scipy import optimize
#import pandas as pd
#from sklearn import linear_model
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure
plt.style.use('seaborn-bright')


def predict(request,student_id):
    
    stud = studentInformation.objects.get(pk=student_id)
    #datafile = 'C:\Django Stuff\mysite\dataVIZ\ex2data1.txt'
    datafile = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),'static/ex2data1.txt')
    #datafile = static('images/ex2data1.txt')
    data = np.loadtxt(datafile,delimiter=',',usecols=(0,1,2),unpack=True)

    X = np.transpose(np.array(data[:-1]))
    y = np.transpose(np.array(data[-1:]))

    #size of data
    m = y.size
    X = np.insert(X,0,1,axis=1)

    #cases where the student gets admitted
    pos = np.array([X[i] for i in range(X.shape[0]) if y[i]==1])

    #cases where the student does not get admitted
    neg = np.array([X[i] for i in range(X.shape[0]) if y[i]==0])

    def plot_data():
        
        fig = plt.figure()
        ax = plt.subplot(111)
        ax.plot(pos[:,1],pos[:,2],'ro',label='Admitted')
        ax.plot(neg[:,1],neg[:,2],'yo',label='Not Admitted')
        #ax.xlabel('Exam 1 Score')
        #ax.ylabel('Exam 2 Score')
        ax.set_xlabel('Exam 1 Score')
        ax.set_ylabel('Exam 2 Score')
        ax.grid('on')
        ax.plot(boundary_xs,boundary_ys,'m-',label='Decision Boundary')
        ax.plot(stud.exam1_marks,stud.exam2_marks,'bo',label= stud.firstname+' '+stud.lastname)
        handles, labels = ax.get_legend_handles_labels()
        lgd = ax.legend(handles, labels, loc=9, bbox_to_anchor=(0.5, -0.1), ncol=2)
        ax.grid('on')
        #fig.savefig('C:\Django Stuff\heroku_deploy\mysite\static\images\imgdata.png',bbox_extra_artists=(lgd,), bbox_inches='tight')
        fig.savefig(os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),'static/images/imgdata.png'),bbox_extra_artists=(lgd,), bbox_inches='tight')
    #
    def hypothesis(mytheta,myX):
        return expit(np.dot(myX,mytheta))

    def computeCost(mytheta,myX,myy,mylamda=0.):
        term1 = np.dot(-np.array(myy).T,np.log(hypothesis(mytheta,myX)))
        term2 = np.dot((1-np.array(myy)).T,np.log(1-hypothesis(mytheta,myX)))
        reg_term = (mylamda/2) * np.sum(np.dot(mytheta[1:].T,mytheta[1:]))
        return float((1./m) * (np.sum(term1 - term2 + reg_term)))

    initial_theta = np.zeros((X.shape[1],1))
    #print initial_theta

    computeCost(initial_theta,X,y)


    def optimizeTheta(mytheta,myX,myy,mylambda=0.):
        result = optimize.fmin(computeCost,x0=mytheta,args=(myX,myy,mylambda),maxiter=400,full_output=True)
        return result[0],result[1]


    theta, minCost = optimizeTheta(initial_theta,X,y)

    def predict(theta,X,threshold=0.5):
        p = expit(np.dot(X,theta.T)) >= threshold
        return p.astype('int')

    p = predict(theta,X)

    #Plotting the decision boundary
    boundary_xs = np.array([np.min(X[:,1]), np.max(X[:,1])])

    #slope of the decision line
    boundary_ys = (-1./theta[2])*(theta[0] + theta[1]*boundary_xs)
    plot_data()

    img = mpimg.imread(os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),'static/images/imgdata.png'))
    context = {'student':stud}

    template = loader.get_template('dataVIZ/prediction.html')
    return HttpResponse(template.render(context,request))

#@csrf
def index(request):
    #return render(request,'dataVIZ/home.html')
    template = loader.get_template('dataVIZ/home.html')
    return HttpResponse(template.render(request))


#def insert(request):
#    return render(request,'dataVIZ/insert.html')

def insert(request):
    template = loader.get_template('dataVIZ/insert.html')
    return HttpResponse(template.render(request))


#def records(request):
    #return render(request,'dataVIZ/records.html',{'all_students':all_records})

def records(request):
    
    all_records = studentInformation.objects.all()
    template = loader.get_template('dataVIZ/records.html')
    context = {
        'all_students':all_records,
    }
    return HttpResponse(template.render(context,request))
    #return render(request,'dataVIZ/records.html',context)



def details(request, student_id):
    
    try:
        all_records = studentInformation.objects.get(pk=student_id)
        template = loader.get_template('dataVIZ/studentDetails.html')
        context = {'student_id':student_id}
        
    except studentInformation.DoesNotExist:
        raise Http404("Student Information Unavailable")
    
    return HttpResponse(template.render(context,request))
        
        #return HttpResponse("<h2>Details for Student id: "+str(student_id)+"</h2>")

        
#-----------------------------------------------------GENERIC VIEWS---------------------------------------------
    
class IndexView(generic.ListView):
    model = studentInformation
    template_name = 'dataVIZ/studentinformation_list.html'
    context_object_name = 'all_students'
    paginate_by = 5
    queryset = studentInformation.objects.all()
    
    def get_queryset(self):
        return studentInformation.objects.all()

    
#class DetailView(generic.DetailView):
#    model = studentInformation
#    template_name = 'dataVIZ/studentDetails.html'
    

class StudentInformationCreate(CreateView):
    model = studentInformation
    fields = ['firstname','lastname','exam1_marks','exam2_marks']
    
    success_url = reverse_lazy('dataVIZ:listview')
    
class StudentUdpate(UpdateView):
    model = studentInformation
    fields = ['firstname','lastname','exam1_marks','exam2_marks']
    
    success_url = reverse_lazy('dataVIZ:listview')
    
class DeleteStudent(DeleteView):
    model = studentInformation
    
    success_url = reverse_lazy('dataVIZ:listview')
    
#------------------------------------------------------------------------------------------------------------------    
    
    
def student_details_page(request, student_id):
   
    stud = studentInformation.objects.get(pk=student_id)
    
    template = loader.get_template('dataVIZ/studentDetails.html')
    
    context = {'student':stud}
    
    return render(request,'dataVIZ/studentDetails.html',context)

    
def post_form_upload(request):
    if request.method == 'POST':
        
        form = studentInformationForm(request.POST)
        
        if form.is_valid():
            firstname = request.POST.get('firstname','')
            lastname = request.POST.get('lastname','')
            exam1_marks = request.POST.get('exam1_marks','')
            exam2_marks = request.POST.get('exam2_marks','')
            
            form_obj = studentInformation(firstname=firstname,
                                         lastname = lastname,
                                         exam1_marks = exam1_marks,
                                         exam2_marks = exam2_marks)
            
            form_obj.save()
            return render(request,'dataVIZ/records.html')
            
    else:
        form = studentInformationForm()

        return render(request,'dataVIZ/insert.html')
    

dataVIZ/templates/dataVIZ/home.html
{% extends "dataVIZ/layout.html" %}
{% load staticfiles %}
{%block content%}

<div class="jumbotron">
  <h1>Logit<span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span></h1>
  <p>Logistic Regression is an appropriate analysis to conduct when the dependent variable is binary, and can be used to describe data and explain the relationship between these dependent variables.</p>
    
  <p>
    Use this tool to predict a <strong>possible outcome of admission</strong> based on two scores (x<sub>1</sub>,x<sub>2</sub>)
  </p>
</div>

</div>
<div class="container" style=" height: 600px; margin: 0 auto">
   
        <img class="col-md-8 col-md-offset-2" src="{% static 'images/home.png' %}" class="img-responsive"/>

</div>

{%endblock%}


dataVIZ/templates/dataVIZ/insert.html
{% extends "dataVIZ\layout.html" %}

{% block content %}

<div class="container">
    <div class="row col-md-6 col-md-offset-3" style="padding-bottom:50px;">
        <h1>Student Information</h1>
    </div>
    
    <form method="post">
        <div class="row col-md-6 col-md-offset-3">
            <div class="form-group">
                <label for="First Name">First Name</label>
                <input type="name" class="form-control" id="firstName" placeholder="First Name/Given Name">
            </div>
            
            <div class="form-group">
                <label for="Last Name">Last Name</label>
                <input type="name" class="form-control" id="lastName" placeholder="Last Name">
            </div>
            
            <div class="form-group">
                <label for="Marks 1">Marks for Exams 1</label>
                <input type="number" min="0" max="100" class="form-control" id="exam1_marks" placeholder="Exam 1 Marks">
            </div>
                
            <div class="form-group">
                <label for="Marks 2">Marks for Exams 2</label>
                <input type="number" min="0" max="100" class="form-control" id="exam2_marks" placeholder="Exam 2 Marks">
            </div>
            
            <input style="margin-top:50px;" type="submit" value="Submit" class="btn btn-primary btn-lg btn-block">
            
        </div>
        
        
    </form>
    
  
  </div>
</div>
</div>

{% endblock %}
<!--


-->

dataVIZ/templates/dataVIZ/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
	<title>Logit

    </title>
	<meta charset="utf-8" />
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type = "text/css"/>
    <link rel="stylesheet" href="{% static 'css/footer-distributed-with-address-and-phones.css' %}" type = "text/css"/>
    
	<meta name="viewport" content = "width=device-width, initial-scale=1.0">

<script
			  src="https://code.jquery.com/jquery-2.2.4.min.js"
			  integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
			  crossorigin="anonymous">
</script>

	<style type="text/css">
		html,
		body {
		  height:100%
		}
        
        input{
            background-color: grey;
            color: white;
            border: none;
            padding: 5px 5px 5px 5px;
            margin-bottom: 5px;
            font:helvetica;
        }
        
        textarea{
            background-color: grey;
            color:white;
            border:none;
            padding: 5px 5px 5px 5px;
            margin-bottom: 5px;
            font: Helvetica;
        }
        
        button{
            background-color: grey;
            color: white;
            border: none;
            border-radius: 5px 5px 5px 5px;
            padding: 5px 5px 5px 5px;
        }
	</style>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

<body class="body" style="background-color:white;">
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Logit
        <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'dataVIZ:addstudent' %}">New Student
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        </a></li>
        <li><a href="/listview/">Student Records
            <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
        </a></li>
        <li><a href="">API
            <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
        </a></li>
      </ul>

    <form class="navbar-form navbar-right">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search Student">
            <button style="margin-bottom:5px;" type="submit" class="btn btn-primary">Go</button>
        </div>
      </form>
        
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
    </body>
    
    
<div class='container-fluid'>
			   {% block content %}
			   {% endblock %}	
</div>
		<footer class="footer-distributed" style="background-color:black; margin: 150px 0 0 0;">

			<div class="footer-left">

				<h3>Log<span>it</span><span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span></h3><br/>

				<p class="footer-company-about">
					<!--<a href="add/" style="text-decoration:none; color:white;">New Student</a>
					·
					<a href="#" style="text-decoration:none; color:white;">Student Record</a>
					·
					<a href="#" style="text-decoration:none; color:white;">Predict</a>-->

				</p><br/><br/>

				<p class="footer-company-name">Logit &copy; 2017</p>
                <p class="footer-company-name">Developed by
                    <a style="color:white; cursor:pointer;" href="https://anish03.github.io/personal/" target="_blank">Anish Narkhede</a>
                </p>
			</div>

			<div class="footer-center">

				<div>
					<i class="fa fa-map-marker"></i>
					<p><span>Kothrud</span> Pune, India</p>
				</div>

				<div>
					<i class="fa fa-phone"></i>
					<p>+91 9765398872</p>
				</div>

			</div>
			<div class="footer-right">

                <div>
                    <a href="https://www.linkedin.com/in/anish-narkhede-42354035/" target="_blank"><i class="fa fa-linkedin fa-3x" aria-hidden="true"></i></a><br/>

                </div><br/>
                <div>
                    <a href="https://www.github.com/anish03/" target="_blank"><i class="fa fa-github fa-3x" aria-hidden="true"></i></a>
                </div>

			</div>


		</footer>
</html>

dataVIZ/templates/dataVIZ/prediction.html
{% extends "dataVIZ/layout.html" %}
{% load staticfiles %}
{% block content %}
<!--<img src="result.png">-->
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script
			  src="https://code.jquery.com/jquery-2.2.4.min.js"
			  integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
			  crossorigin="anonymous">
</script>

<div style="margin-left:50px;">
  <h1>{{student.firstname}} <small>{{student.lastname}}</small></h1>
</div><br/>

<div class="row">
    <div id="container" class="col-md-6" style="min-width: 310px; height: 550px; margin: 0 auto">

    </div>

    <div class="col-md-6">
            <img src="{% static 'images/imgdata.png' %}" class="img-responsive"/>
    </div>
</div>


<script>

$(function () {
    Highcharts.chart('container', {
        chart: {
            type: 'column'
        },
        title: {
            text: 'Test Performance'
        },
        xAxis: {
            categories: [
                'Subjects'
            ],
            crosshair: true
        },
        yAxis: {
            min: 0,
            max: 100,
            title: {
                text: 'Exam Score (out of 100)'
            }
        },
        tooltip: {
            headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
            pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                '<td style="padding:0"><b>{point.y:.1f}</b></td></tr>',
            footerFormat: '</table>',
            shared: true,
            useHTML: true
        },
        plotOptions: {
            column: {
                pointPadding: 0.2,
                borderWidth: 0
            }
        },
        series: [{
            name: 'Exam 1 Score',
            data: [{{student.exam1_marks}}]

        }, {
            name: 'Exam 2 Score',
            data: [{{student.exam2_marks}}]
        }]
    });
});

</script>
{% endblock %}


dataVIZ/templates/dataVIZ/records.html
{% extends "dataVIZ\layout.html" %}

{% block content %}
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    {% load staticfiles %}
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="{% static 'dataVIZ/vendors/jquery/dist/jquery.min.js' %}"></script>

    <title>Student Records</title>

<style>
    .table td{
        text-align: center;
    }
    
    .table th{
        text-align: center;
    }
    
    tr{
        cursor: pointer;
    }
    
</style>
    
</head>
    <!--<tr onclick="window.location='/studentDetails/{{student.id}}/'">-->
    <table id="datatable" class="table table-hover table-bordered">
        <thead>
            <tr> 
                <th>First Name</th>
                <th>Last Name</th>
                <th>Exam 1 Score</th>
                <th>Exam 2 Score</th>
            </tr>
        </thead>
        {% for student in all_students %}
        <tr onclick="window.location='/studentDetails/{{student.id}}/'">
            <td>{{student.firstname}}</td>
            <td>{{student.lastname}}</td>
            <td>{{student.exam1_marks}}</td>
            <td>{{student.exam2_marks}}</td>
            </tr>
        {% endfor %}
        
    </table>

<script>
    
    $(function(){
        $('table.table table-hover table-bordered tr').click(function(){
            window.location.href=$(this).data('insert.html');
        });
    })
    
</script>

{%endblock%}

dataVIZ/templates/dataVIZ/studentDetails.html
{% extends "dataVIZ/layout.html" %}

{% block content %}
<div style="margin-left:50px;" class="page-header">
  <h1>{{student.firstname}} <small>{{student.lastname}}</small></h1>
</div>


<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script
			  src="https://code.jquery.com/jquery-2.2.4.min.js"
			  integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
			  crossorigin="anonymous">
</script>

<div id="container" style="min-width: 310px; height: 500px; margin: 0 auto">

</div>

<script>

$(function () {
    Highcharts.chart('container', {
        chart: {
            type: 'column'
        },
        title: {
            text: 'Test Performance'
        },
        xAxis: {
            categories: [
                'Subjects'
            ],
            crosshair: true
        },
        yAxis: {
            min: 0,
            max: 100,
            title: {
                text: 'Exam Score (out of 100)'
            }
        },
        tooltip: {
            headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
            pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                '<td style="padding:0"><b>{point.y:.1f}</b></td></tr>',
            footerFormat: '</table>',
            shared: true,
            useHTML: true
        },
        plotOptions: {
            column: {
                pointPadding: 0.2,
                borderWidth: 0
            }
        },
        series: [{
            name: 'Exam 1 Score',
            data: [{{student.exam1_marks}}]

        }, {
            name: 'Exam 2 Score',
            data: [{{student.exam2_marks}}]
        }]
    });
});

</script>

{% endblock %}

dataVIZ/templates/dataVIZ/studentinformation_form.html
{% extends "dataVIZ/layout.html" %}
{% load widget_tweaks %}

{% block content %}

<style>

    .spacing{
        margin-top: 10px;
        margin-bottom: 10px;
    }


</style>



<br/><br/>
<div class="container">
    <div class="row col-md-6 col-md-offset-3">
        <h1>Student Information</h1>
    
        
    <form style="margin-top:40px;" method="post" action="" enctype="multipart/form-data">
        <!--{{form.as_p}}-->
        {% csrf_token %}
        
            {% for field in form %}
            {{field.label_tag}}
            
            {% if field.errors %}
                <div class="alert alert-danger" role="alert">
                      <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                      <span class="sr-only">Error:</span>
                        {{field.errors}}
                </div>
            {% endif %}
        
            {{ field | add_class:"form-control" | add_class:"spacing"}}
        
        
        {% endfor %}          
        <input style="margin-top:50px;" type="submit" value="Save" class="btn btn-primary btn-lg btn-block">
    </form>
    </div>
  </div>

{% endblock %}

dataVIZ/templates/dataVIZ/studentinformation_list.html
{% extends "dataVIZ/layout.html" %}

{% block content %}
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Student Records</title>

<style>
    .table td{
        text-align: center;
    }

    .table th{
        text-align: center;
        height:30px;
    }

    tr{
        cursor: pointer;
        height: 70px;
    }

    .paginator_style{
        position: relative;
        top: 50%;
        margin-top: 10px;
        margin-left: 45%;
    }


    table{
        border: none;
    }

</style>

</head>
<br/><br/>
    <!---->
    <!--<tr onclick="window.location='/studentDetails/{{student.id}}/'">-->
    <table id="datatable" class="table table-hover table-striped" >
    <thead>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Exam 1 Score</th>
                <th>Exam 2 Score</th>
                <th>Action</th>

    </thead>
        {% for student in all_students %}
        <tr >
            <td onclick="window.location='/studentDetails/{{student.id}}/'">{{student.firstname}}</td>
            <td onclick="window.location='/studentDetails/{{student.id}}/'">{{student.lastname}}</td>
            <td onclick="window.location='/studentDetails/{{student.id}}/'">{{student.exam1_marks}}</td>
            <td onclick="window.location='/studentDetails/{{student.id}}/'">{{student.exam2_marks}}</td>
            <td>
                <form action="{% url 'dataVIZ:delete-student' student.id %}" method="post" style="display:inline;">
                    {% csrf_token %}

                    <input type="hidden" name="student_id" value="{{student.id}}"/>
                    <button type="submit" class="btn btn-default btn-sm">
                        <span class="glyphicon glyphicon-trash"></span>
                    </button>
                </form>

                <div style="display:inline;">
                    <button onclick="window.location='/update/{{student.id}}/'" type="button" class="btn btn-default btn-sm">
                        <span class="glyphicon glyphicon-pencil"></span>
                    </button>

                </div>
                <div style="display:inline;">
                    <button onclick="window.location='/predict/{{student.id}}/'" type="button" class="btn btn-default btn-sm">
                        <span class="glyphicon glyphicon-stats" style="font-family: Helvetica;"> Predict</span>
                    </button>

                </div>
            </td>
            </tr>

        {% endfor %}

    </table>
    <div class="paginator_style">

        {% if is_paginated %}
          <ul class="pagination">
            {% if page_obj.has_previous %}
              <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
            {% else %}
              <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in paginator.page_range %}
              {% if page_obj.number == i %}
                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
              {% else %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
              {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
              <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
            {% else %}
              <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
          </ul>
        {% endif %}

    </div>

{% endblock %}